Repository go-vela/docs, pull requests merged in 2020-01, with the labels that each got.

#41 feat: add git plugin docs
  .gitignore
  content/plugins/registry/git.md
Labels: feature

#42 feat: add docker plugin docs
  content/plugins/registry/docker.md
  content/plugins/registry/git.md
Labels: feature

#44 refactor(cli): move content to separate section
  content/cli/_index.md
  content/cli/authentication.md
  content/cli/build/_index.md
  content/cli/build/get.md
  content/cli/build/view.md
  content/cli/config/_index.md
  content/cli/config/remove.md
  content/cli/config/update.md
  content/cli/config/view.md
  content/cli/generate/_index.md
  content/cli/generate/config.md
  content/cli/generate/pipe.md
  content/cli/install.md
  content/cli/log/_index.md
  content/cli/log/view.md
  content/cli/repo/_index.md
  content/cli/repo/add.md
  content/cli/repo/chown.md
  content/cli/repo/get.md
  content/cli/repo/remove.md
  content/cli/repo/repair.md
  content/cli/repo/update.md
  content/cli/repo/view.md
  content/cli/secret/_index.md
  content/cli/secret/add.md
  content/cli/secret/get.md
  content/cli/secret/remove.md
  content/cli/secret/update.md
  content/cli/secret/view.md
  content/cli/service/_index.md
  content/cli/service/get.md
  content/cli/service/view.md
  content/cli/step/_index.md
  content/cli/step/get.md
  content/cli/step/view.md
  content/cli/validate.md
  layouts/cli/baseof.html
  layouts/cli/list.html
  layouts/cli/single.html
Labels: enhancement

#43 refactor(api): move content to separate section
  content/api/_index.md
  content/api/authentication.md
  content/api/build/_index.md
  content/api/build/create.md
  content/api/build/get.md
  content/api/build/logs.md
  content/api/build/remove.md
  content/api/build/restart.md
  content/api/build/update.md
  content/api/build/view.md
  content/api/repo/_index.md
  content/api/repo/chown.md
  content/api/repo/create.md
  content/api/repo/get.md
  content/api/repo/remove.md
  content/api/repo/repair.md
  content/api/repo/update.md
  content/api/repo/view.md
  content/api/secret/_index.md
  content/api/secret/create.md
  content/api/secret/get.md
  content/api/secret/remove.md
  content/api/secret/update.md
  content/api/secret/view.md
  content/api/service/_index.md
  content/api/service/create.md
  content/api/service/get.md
  content/api/service/logs.md
  content/api/service/remove.md
  content/api/service/update.md
  content/api/service/view.md
  content/api/step/_index.md
  content/api/step/create.md
  content/api/step/get.md
  content/api/step/logs.md
  content/api/step/remove.md
  content/api/step/update.md
  content/api/step/view.md
  layouts/api/baseof.html
  layouts/api/list.html
  layouts/api/single.html
Labels: enhancement

#45 feat: suppress child elements on sidebar
  config.toml
Labels: feature

#46 refactor: update API authentication content
  content/api/authentication.md
Labels: enhancement

#48 feat: add artifactory plugin docs
  content/plugins/registry/artifactory.md
Labels: feature

#53 feat: add API user content
  content/api/user/_index.md
  content/api/user/add.md
  content/api/user/get.md
  content/api/user/remove.md
  content/api/user/update.md
  content/api/user/view.md
Labels: feature

#54 feat: add API hook content
  content/api/hook/_index.md
  content/api/hook/add.md
  content/api/hook/get.md
  content/api/hook/remove.md
  content/api/hook/update.md
  content/api/hook/view.md
Labels: feature

#55 refactor: update CLI install content
  content/cli/install.md
Labels: enhancement

#56 refactor: update CLI authentication content
  content/cli/authentication.md
Labels: enhancement

#57 refactor: update CLI validate content
  content/cli/validate.md
Labels: enhancement

#58 refactor: update CLI build content
  content/cli/build/_index.md
  content/cli/build/get.md
  content/cli/build/view.md
Labels: enhancement

#59 refactor(api): add link to authentication section
  content/api/build/_index.md
  content/api/build/add.md
  content/api/build/get.md
  content/api/build/logs.md
  content/api/build/remove.md
  content/api/build/restart.md
  content/api/build/update.md
  content/api/build/view.md
  content/api/hook/_index.md
  content/api/hook/add.md
  content/api/hook/get.md
  content/api/hook/remove.md
  content/api/hook/update.md
  content/api/hook/view.md
  content/api/repo/_index.md
  content/api/repo/add.md
  content/api/repo/chown.md
  content/api/repo/get.md
  content/api/repo/remove.md
  content/api/repo/repair.md
  content/api/repo/update.md
  content/api/repo/view.md
  content/api/secret/_index.md
  content/api/secret/add.md
  content/api/secret/get.md
  content/api/secret/remove.md
  content/api/secret/update.md
  content/api/secret/view.md
  content/api/service/_index.md
  content/api/service/add.md
  content/api/service/get.md
  content/api/service/logs.md
  content/api/service/remove.md
  content/api/service/update.md
  content/api/service/view.md
  content/api/step/_index.md
  content/api/step/add.md
  content/api/step/get.md
  content/api/step/logs.md
  content/api/step/remove.md
  content/api/step/update.md
  content/api/step/view.md
  content/api/user/_index.md
  content/api/user/add.md
  content/api/user/get.md
  content/api/user/remove.md
  content/api/user/update.md
  content/api/user/view.md
Labels: enhancement

#60 refactor: update CLI config content
  content/cli/config/_index.md
  content/cli/config/remove.md
  content/cli/config/update.md
  content/cli/config/view.md
Labels: enhancement

#62 fix: getting started links
  content/usage/getting-started/authenticate.md
  content/usage/getting-started/enable_repo.md
Labels: bug

#63 refactor: update CLI repo content
  content/cli/repo/_index.md
  content/cli/repo/add.md
  content/cli/repo/chown.md
  content/cli/repo/get.md
  content/cli/repo/remove.md
  content/cli/repo/repair.md
  content/cli/repo/update.md
  content/cli/repo/view.md
Labels: enhancement

#64 fix(cli): resolve formatting for links
  content/cli/build/_index.md
  content/cli/build/get.md
  content/cli/build/view.md
  content/cli/config/_index.md
  content/cli/config/remove.md
  content/cli/config/update.md
  content/cli/config/view.md
Labels: bug

#61 refactor: update CLI log content
  content/cli/log/_index.md
  content/cli/log/view.md
Labels: enhancement

#65 refactor: update CLI secret content
  content/cli/secret/_index.md
  content/cli/secret/add.md
  content/cli/secret/get.md
  content/cli/secret/remove.md
  content/cli/secret/update.md
  content/cli/secret/view.md
Labels: enhancement

#66 refactor: update CLI service content
  content/cli/service/_index.md
  content/cli/service/get.md
  content/cli/service/view.md
Labels: enhancement

#68 feat: add CLI config generate content
  content/cli/config/generate.md
  content/cli/generate/config.md
Labels: feature

#67 refactor: update CLI step content
  content/cli/step/_index.md
  content/cli/step/get.md
  content/cli/step/view.md
Labels: enhancement

#69 refactor: update Plugins overview content
  content/plugins/_index.md
  content/plugins/getting-started/_index.md
  content/plugins/getting-started/how-to.md
  content/plugins/getting-started/what-is.md
  content/plugins/overview.md
Labels: enhancement

#70 refactor: update Plugins registry content
  content/plugins/registry/_index.md
  content/plugins/registry/artifactory.md
  content/plugins/registry/docker.md
  content/plugins/registry/git.md
Labels: enhancement

#71 feat: add Plugin tutorials content
  content/plugins/tutorials/_index.md
  content/plugins/tutorials/bash.md
  content/plugins/tutorials/go.md
Labels: feature

#72 refactor(cli): update syntax for supported config parameters
  content/cli/build/get.md
  content/cli/build/view.md
  content/cli/log/view.md
  content/cli/repo/add.md
  content/cli/repo/chown.md
  content/cli/repo/remove.md
  content/cli/repo/repair.md
  content/cli/repo/update.md
  content/cli/repo/view.md
  content/cli/secret/add.md
  content/cli/secret/get.md
  content/cli/secret/remove.md
  content/cli/secret/update.md
  content/cli/secret/view.md
  content/cli/service/get.md
  content/cli/service/view.md
  content/cli/step/get.md
  content/cli/step/view.md
Labels: enhancement

#74 feat: add ruby Plugin tutorials content
  content/plugins/tutorials/ruby.md
Labels: feature

#75 feat: add python Plugin tutorials content
  content/plugins/tutorials/python.md
Labels: feature

#78 feat: add API current user content
  content/api/user/current/_index.md
  content/api/user/current/repos.md
  content/api/user/current/update.md
  content/api/user/current/view.md
Labels: feature

#79 refactor: move CLI generate pipeline content
  content/cli/generate/_index.md
  content/cli/generate/pipe.md
  content/cli/pipeline/_index.md
  content/cli/pipeline/generate.md
Labels: enhancement

#80 refactor(sdk): move content to separate section
  content/api/_index.md
  content/cli/_index.md
  content/plugins/_index.md
  content/sdk/_index.md
  content/sdk/go/_index.md
  content/sdk/go/authentication.md
  content/sdk/go/install.md
  content/usage/_index.md
  content/usage/reference/sdk/_index.md
  content/usage/reference/sdk/authentication.md
  content/usage/reference/sdk/build.md
  content/usage/reference/sdk/install.md
  content/usage/reference/sdk/log.md
  content/usage/reference/sdk/repo.md
  content/usage/reference/sdk/secret.md
  content/usage/reference/sdk/service.md
  content/usage/reference/sdk/step.md
  layouts/sdk/baseof.html
  layouts/sdk/list.html
  layouts/sdk/single.html
Labels: enhancement

#77 refactor: sync plugin tutorial content
  content/plugins/overview.md
  content/plugins/tutorials/_index.md
  content/plugins/tutorials/bash.md
  content/plugins/tutorials/go.md
  content/plugins/tutorials/python.md
  content/plugins/tutorials/ruby.md
Labels: enhancement

#76 feat: add Node.js Plugin tutorials content
  content/plugins/tutorials/node.md
Labels: feature

#81 feat: add Go SDK build content
  content/sdk/go/build/_index.md
  content/sdk/go/build/add.md
  content/sdk/go/build/get.md
  content/sdk/go/build/logs.md
  content/sdk/go/build/remove.md
  content/sdk/go/build/restart.md
  content/sdk/go/build/update.md
  content/sdk/go/build/view.md
Labels: feature

#82 feat: add Go SDK repo content
  content/sdk/go/build/_index.md
  content/sdk/go/repo/_index.md
  content/sdk/go/repo/add.md
  content/sdk/go/repo/chown.md
  content/sdk/go/repo/get.md
  content/sdk/go/repo/remove.md
  content/sdk/go/repo/repair.md
  content/sdk/go/repo/update.md
  content/sdk/go/repo/view.md
Labels: feature

#84 feat: add Go SDK step content
  content/sdk/go/step/_index.md
  content/sdk/go/step/add.md
  content/sdk/go/step/get.md
  content/sdk/go/step/logs.md
  content/sdk/go/step/remove.md
  content/sdk/go/step/update.md
  content/sdk/go/step/view.md
Labels: feature

#85 feat: add Go SDK secret content
  content/sdk/go/secret/_index.md
  content/sdk/go/secret/add.md
  content/sdk/go/secret/get.md
  content/sdk/go/secret/remove.md
  content/sdk/go/secret/update.md
  content/sdk/go/secret/view.md
Labels: feature

#83 feat: add Go SDK service content
  content/sdk/go/service/_index.md
  content/sdk/go/service/add.md
  content/sdk/go/service/get.md
  content/sdk/go/service/logs.md
  content/sdk/go/service/remove.md
  content/sdk/go/service/update.md
  content/sdk/go/service/view.md
Labels: feature

#86 feat: add shell files for concepts
  content/usage/concepts/_index.md
  content/usage/concepts/build.md
  content/usage/concepts/command.md
  content/usage/concepts/compiler.md
  content/usage/concepts/config.md
  content/usage/concepts/environment.md
  content/usage/concepts/hook.md
  content/usage/concepts/image.md
  content/usage/concepts/log.md
  content/usage/concepts/parameter.md
  content/usage/concepts/pipeline.md
  content/usage/concepts/plugin.md
  content/usage/concepts/repo.md
  content/usage/concepts/ruleset.md
  content/usage/concepts/secret.md
  content/usage/concepts/server.md
  content/usage/concepts/service.md
  content/usage/concepts/stage.md
  content/usage/concepts/step.md
  content/usage/concepts/template.md
  content/usage/concepts/token.md
  content/usage/concepts/version.md
  content/usage/concepts/worker.md
  content/usage/concepts/workspace.md
Labels: feature

#87 feat: add references for resource concepts
  content/usage/concepts/build.md
  content/usage/concepts/config.md
  content/usage/concepts/event.md
  content/usage/concepts/hook.md
  content/usage/concepts/log.md
  content/usage/concepts/metadata.md
  content/usage/concepts/repo.md
  content/usage/concepts/secret.md
  content/usage/concepts/service.md
  content/usage/concepts/status.md
  content/usage/concepts/step.md
  content/usage/concepts/user.md
Labels: feature

#88 chore: sync content with plugin tutorial repo
  content/plugins/tutorials/node.md
Labels: enhancement

#89 feat: add shell files for templates
  content/templates/_index.md
  content/templates/registry/_index.md
  content/templates/tutorials/_index.md
  layouts/templates/baseof.html
  layouts/templates/list.html
  layouts/templates/single.html
Labels: feature
