Repository go-vela/docs, pull requests merged in 2020-08, with the labels that each got.

#151 feat: add pattern matcher for ruleset
  content/concepts/pipeline/steps/ruleset.md
  content/usage/pipeline/steps/ruleset.md
Labels: feature

#152 refactor(plugins): prepare plugins for secrets
  content/plugins/overview.md
  content/plugins/pipeline/_index.md
  content/plugins/pipeline/registry/_index.md
  content/plugins/pipeline/registry/artifactory.md
  content/plugins/pipeline/registry/captains_log.md
  content/plugins/pipeline/registry/docker.md
  content/plugins/pipeline/registry/downstream.md
  content/plugins/pipeline/registry/git.md
  content/plugins/pipeline/registry/kubernetes.md
  content/plugins/pipeline/registry/s3_cache.md
  content/plugins/pipeline/registry/terraform.md
  content/plugins/pipeline/tutorials/_index.md
  content/plugins/pipeline/tutorials/bash.md
  content/plugins/pipeline/tutorials/go.md
  content/plugins/pipeline/tutorials/node.md
  content/plugins/pipeline/tutorials/python.md
  content/plugins/pipeline/tutorials/ruby.md
  content/plugins/secret/_index.md
  content/plugins/secret/registry/_index.md
  content/plugins/secret/tutorials/_index.md
Labels: enhancement

#150 refactor(usage): update usage to be focused on using vela concepts
  .gitignore
  content/concepts/pipeline/steps/commands.md
  content/concepts/pipeline/steps/ruleset.md
  content/usage/getting-started/workspace.md
  content/usage/getting-started/write_pipeline.md
  content/usage/pipeline/_index.md
  content/usage/pipeline/examples/_index.md
  content/usage/pipeline/examples/golang.md
  content/usage/pipeline/examples/java.md
  content/usage/pipeline/examples/node.md
  content/usage/pipeline/metadata/_index.md
  content/usage/pipeline/metadata/template.md
  content/usage/pipeline/stages.md
  content/usage/pipeline/steps/_index.md
  content/usage/pipeline/steps/commands.md
  content/usage/pipeline/steps/environment.md
  content/usage/pipeline/steps/image.md
  content/usage/pipeline/steps/parameters.md
  content/usage/pipeline/steps/secrets.md
  content/usage/pipeline/version.md
  content/usage/samples/_index.md
  content/usage/samples/golang.md
  content/usage/samples/java.md
  content/usage/samples/node.md
Labels: enhancement

#155 fix: remove old docs
  content/usage/pipeline/steps/ruleset.md
Labels: bug

#154 feat: add concept docs for worker routing
  content/concepts/pipeline/worker/_index.md
  content/concepts/pipeline/worker/flavor.md
  content/concepts/pipeline/worker/platform.md
Labels: feature

#157 feat: add skip ci section
  content/usage/getting-started/skipping_build.md
  content/usage/getting-started/workspace.md
Labels: feature

#162 enhancement(env): add usage example plus add all default vars
  content/concepts/pipeline/services/environment.md
  content/concepts/pipeline/steps/environment.md
  content/usage/getting-started/environment.md
Labels: enhancement
