Repository go-vela/docs, pull requests merged in 2020-05, with the labels that each got.

#127 feat(api): add deployment endpoints
  content/api/deployment/_index.md
  content/api/deployment/add.md
  content/api/deployment/get.md
  content/api/deployment/view.md
Labels: feature

#129 feat(cli): add deployment commands
  content/cli/deployment/_index.md
  content/cli/deployment/add.md
  content/cli/deployment/get.md
  content/cli/deployment/view.md
Labels: feature

#132 feat: add deployment target
  content/concepts/pipeline/steps/environment.md
  content/concepts/pipeline/steps/ruleset.md
  content/usage/pipeline/steps/ruleset.md
Labels: feature

#133 chore: upgrade plugin versions
  content/plugins/registry/docker.md
  content/plugins/registry/downstream.md
  content/plugins/registry/s3_cache.md
Labels: enhancement

#136 chore: add Apache license
  .github/README.md
  LICENSE
Labels: enhancement

#137 fix(links): fix various links
  content/_index.html
  content/concepts/pipeline/_index.md
  content/concepts/system/hook.md
  content/concepts/system/user.md
  content/sdk/go/build/_index.md
  content/sdk/go/build/add.md
  content/sdk/go/build/get.md
  content/sdk/go/build/logs.md
  content/sdk/go/build/remove.md
  content/sdk/go/build/restart.md
  content/sdk/go/build/update.md
  content/sdk/go/build/view.md
  content/sdk/go/repo/add.md
  content/sdk/go/repo/chown.md
  content/sdk/go/repo/get.md
  content/sdk/go/repo/remove.md
  content/sdk/go/repo/repair.md
  content/sdk/go/repo/update.md
  content/sdk/go/repo/view.md
  content/sdk/go/secret/_index.md
  content/sdk/go/secret/add.md
  content/sdk/go/secret/get.md
  content/sdk/go/secret/remove.md
  content/sdk/go/secret/update.md
  content/sdk/go/secret/view.md
  content/sdk/go/service/add.md
  content/sdk/go/service/get.md
  content/sdk/go/service/logs.md
  content/sdk/go/service/remove.md
  content/sdk/go/service/update.md
  content/sdk/go/service/view.md
  content/sdk/go/step/add.md
  content/sdk/go/step/get.md
  content/sdk/go/step/logs.md
  content/sdk/go/step/remove.md
  content/sdk/go/step/update.md
  content/sdk/go/step/view.md
Labels: bug

#138 docs: divert bugs and features to community
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/not_here.md
Labels: enhancement
