Repository go-vela/docs, pull requests merged in 2022-12, with the labels that each got.

#306 enhance(templates): add deployment parameter details
  content/templates/tutorials/go/vars_platform.md
  content/templates/tutorials/starlark/vars_platform.md
Labels: enhancement, next

#337 feat: document executor.log_streaming_timeout worker arg
  content/installation/worker/reference/executor.md
Labels: documentation, next

#339 chore(templates): add docs for file type template usage
  content/reference/yaml/templates.md
Labels: next

#340 chore(stages): add docs for independent tag
  content/reference/yaml/stages.md
  content/tour/stages.md
Labels: next

#341 chore(api/build): add docs for get build by id
  content/reference/api/build/view.md
Labels: next
