Repository go-vela/docs, pull requests merged in 2024-06, with the labels that each got.

#405 feat(rulesets): explain PR labeled and unlabeled events
  content/reference/api/admin/secret.md
  content/reference/api/repo/add.md
  content/reference/api/repo/get.md
  content/reference/api/repo/update.md
  content/reference/api/repo/view.md
  content/reference/api/secret/add.md
  content/reference/api/secret/get.md
  content/reference/api/secret/update.md
  content/reference/api/secret/view.md
  content/reference/yaml/steps.md
  content/usage/repo_settings.md
Labels: feature, next

#412 feat(schedules): update API response examples
  content/reference/api/schedule/add.md
  content/reference/api/schedule/get.md
  content/reference/api/schedule/remove.md
  content/reference/api/schedule/update.md
  content/reference/api/schedule/view.md
  content/reference/cli/schedule/add.md
  content/reference/cli/schedule/get.md
  content/reference/cli/schedule/remove.md
  content/reference/cli/schedule/update.md
  content/reference/cli/schedule/view.md
Labels: enhancement, next

#413 feat(dashboard): add dashboard commands to cli reference
  content/reference/cli/dashboard/_index.md
  content/reference/cli/dashboard/add.md
  content/reference/cli/dashboard/get.md
  content/reference/cli/dashboard/update.md
  content/reference/cli/dashboard/view.md
Labels: next

#418 docs(cli): add ruleset data params, and other missing params to validate
  content/reference/cli/pipeline/validate.md
Labels: next

#410 feat(reference): platform settings
  content/reference/api/admin/settings/_index.md
  content/reference/api/admin/settings/restore.md
  content/reference/api/admin/settings/update.md
  content/reference/api/admin/settings/view.md
  content/reference/cli/settings/_index.md
  content/reference/cli/settings/update.md
  content/reference/cli/settings/view.md
Labels: next

#408 chore: add step status docs
  content/reference/environment/variables.md
  content/reference/yaml/steps.md
  content/tour/status.md
Labels: next

#414 chore(db): add database logging flags
  content/installation/server/reference/_index.md
  content/installation/server/reference/database.md
Labels: next

#419 feat: platform settings usage/admin docs
  content/installation/server/reference/_index.md
  content/installation/server/reference/compiler.md
  content/installation/server/reference/settings.md
  content/templates/tutorials/starlark/functions.md
Labels: next
